[setup]
boxlength		= 100
zstart			= 50
levelmin		= 6
levelmin_TF		= 6
levelmax		= 8
padding			= 8
overlap			= 4
region			= multibox
region_point_file	= /home/kjhan/BACKUP/LagMUSIC/music/test_multibox_points.txt
region_point_level	= 6
align_top		= no
baryons			= no
use_2LPT		= no
use_LLA			= no
periodic_TF		= yes
kspace_TF		= yes
slab_levelmin_density	= yes

[cosmology]
Omega_m			= 0.276
Omega_L			= 0.724
w0			= -1.0
wa			= 0.0
Omega_b			= 0.045
H0			= 70.3
sigma_8			= 0.811
nspec			= 0.961
transfer		= eisenstein

[random]
seed[6]			= 12345
seed[7]			= 23456
seed[8]			= 34567

[output]
format			= generic
filename		= /tmp/test_mb_h4_c1_on.hdf5

[poisson]
fft_fine		= yes
accuracy		= 1e-5
pre_smooth		= 3
post_smooth		= 3
smoother		= gs
laplace_order		= 6
grad_order		= 6
