[setup]
boxlength		= 100
zstart			= 50
levelmin		= 8
levelmin_TF		= 8
levelmax		= 9
padding			= 4
overlap			= 2
region			= multibox
region_point_file	= /tmp/centered_pts.txt
region_point_level	= 8
align_top		= no
baryons			= no
use_2LPT		= no
use_LLA			= no
periodic_TF		= yes
kspace_TF       = yes
rng_per_cluster = yes

[cosmology]
Omega_m			= 0.276
Omega_L			= 0.724
w0			= -1.0
wa			= 0.0
Omega_b			= 0.045
H0			= 70.3
sigma_8			= 0.811
nspec			= 0.961
transfer		= eisenstein

[random]
seed[8]			= 12345
seed[9]			= 23456

[output]
format			= generic
filename		= /tmp/test_multibox_g3c_pos2.hdf5

[poisson]
fft_fine		= yes
accuracy		= 1e-5
pre_smooth		= 3
post_smooth		= 3
smoother		= gs
laplace_order		= 6
grad_order		= 6
